name: Build and Delivery

on:
  workflow_run:
    workflows: ["Test Python App"]
    branches: [main]
    types: [completed]

jobs:
  cd:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          path: 'devops-lab5-main/devops-lab5-main'

      - name: Verify Dockerfile
        run: |
          cd devops-lab5-main/devops-lab5-main
          ls -la
          echo "Dockerfile content:"
          cat Dockerfile
          echo "Requirements:"
          cat requirements.txt

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: devops-lab5-main/devops-lab5-main
          file: devops-lab5-main/devops-lab5-main/Dockerfile
          push: true
          tags: |
            ${{ vars.DOCKERHUB_USERNAME }}/my-app:latest
            ${{ vars.DOCKERHUB_USERNAME }}/my-app:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max